[package]
name = "redirection-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
redis = "0.25"
tokio = { version = "1.37", features = ["full"] }